const GAME_CONSTANTS = {
  CUBE_SIZE: 30,
  PLATFORM_WIDTH: 80,
  PLATFORM_HEIGHT: 30,
  BASE_PLATFORM_Y: 570, // 600 - 30 (platform height)
  PLAYER_MOVEMENT_SPEED: 200,
  JUMP_VELOCITY: -300,
  GRAVITY: 500,
};
export default GAME_CONSTANTS;